numpy与pytorch的区别

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
np_data = np.arange(6).reshape((2, 3))

In [5]:
torch_data = torch.from_numpy(np_data)

In [8]:
print(
    '\nnumpy', np_data,
    '\ntorch', torch_data,
)


numpy [[0 1 2]
 [3 4 5]] 
torch tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)


In [12]:
tensor2arry = torch_data.numpy()

In [25]:
print(
    '\nnumpy', np_data,
    '\ntorch', torch_data,
    '\ntensor2arry', tensor2arry
)


numpy [[0 1 2]
 [3 4 5]] 
torch tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor2arry [[0 1 2]
 [3 4 5]]


abs

In [19]:
import torch

In [22]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)           # 32bit
print(
    '\nabs', 
    '\nnumpy', np.abs(data),           # [1 2 1 2]
    '\ntorch', torch.abs(tensor)        # [1 2 1 2]
)


abs 
numpy [1 2 1 2] 
torch tensor([1., 2., 1., 2.])


In [24]:
print(
    '\nsin', 
    '\nnumpy', np.sin(data),           # [1 2 1 2]
    '\ntorch', torch.sin(tensor)        # [1 2 1 2]
)


sin 
numpy [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [28]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)           # 32bit
print(

    '\nnumpy', np.matmul(data, data),   
    '\ntorch', torch.mm(tensor, tensor)     
   
)


numpy [[ 7 10]
 [15 22]] 
torch tensor([[ 7., 10.],
        [15., 22.]])


In [38]:
data = [1, 2]
tensor = torch.FloatTensor(data)           # 32-bit floating point
data = np.array(data)
print(
    '\nnumpy:', data.dot(data),
    '\ntorch:', tensor.dot(tensor)     
)


numpy: 5 
torch: tensor(5.)
